{% set name = "autopxd2" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: 823b72cbb3953bafd9c02b81d373e8ece937e0054f5cdf5be96b62a39d9ee91a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - pycparser
    - python >=3.6

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  # Drop vendored license file once this upstream issue is addressed
  # xref: https://github.com/gabrieldemarmiesse/python-autopxd2/issues/26
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
